on:
  workflow_call:
  repository_dispatch:
    types:
      - docs_publish
  release:
    types:
      - released
name: Documentation
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3

    - name: Build documentation
      run: make docs-build

    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: ./build/docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
